spring:
  application:
    name: air-ticket-service
  config:
    import: optional:file:app.env[.properties]
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: jdbc:postgresql://localhost:5432/booking
    username: postgres
    password: root
    driverClassName: org.postgresql.Driver

server:
  port: 1111


#  cloud:
#    gateway:
#      discovery:
#        locator:
#          enabled: true
#    config:
#      uri: http://localhost:8080
#      fail-fast: true