spring:
  config:
    import: optional:file:app.env[.properties]
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: jdbc:postgresql://localhost:5432/booking
    username: postgres
    password: root
    driverClassName: org.postgresql.Driver

server:
  port: 1111